import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Zap, TrendingDown, Lightbulb } from 'lucide-react';
import { Layout, Button } from '../components/Layout';
import { Card, Header } from '../components/Card';
import { XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts';
const healthData = [
    { month: 'Jan', soh: 100 },
    { month: 'Feb', soh: 99.5 },
    { month: 'Mar', soh: 99 },
    { month: 'Apr', soh: 98.5 },
    { month: 'May', soh: 97.8 },
    { month: 'Jun', soh: 97.2 },
    { month: 'Jul', soh: 96.8 },
    { month: 'Aug', soh: 96.2 },
];
const degradationData = [
    { cycle: '0-500', rate: 0.5 },
    { cycle: '500-1000', rate: 0.45 },
    { cycle: '1000-1500', rate: 0.48 },
    { cycle: '1500-2000', rate: 0.52 },
    { cycle: '2000-2500', rate: 0.55 },
];
export default function AIBatteryHealthScreen() {
    const navigate = useNavigate();
    return (_jsxs(Layout, { title: "Battery Health", children: [_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, children: _jsx(Header, { title: "AI Battery Health Analysis", subtitle: "Machine learning predictions and degradation analysis", icon: _jsx(Zap, {}) }) }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-12", children: [_jsxs(Card, { className: "p-8 text-center relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 w-40 h-40 bg-emerald-500/10 rounded-full -mr-20 -mt-20" }), _jsx("p", { className: "text-primary-400 text-sm font-semibold mb-3", children: "STATE OF HEALTH (SOH)" }), _jsx("div", { className: "text-5xl font-bold text-emerald-500 mb-2", children: "94%" }), _jsx("p", { className: "text-primary-400 text-sm", children: "Healthy - Expected life: 8-10 years" })] }), _jsxs(Card, { className: "p-8 text-center relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 w-40 h-40 bg-yellow-500/10 rounded-full -mr-20 -mt-20" }), _jsx("p", { className: "text-primary-400 text-sm font-semibold mb-3", children: "STATE OF CHARGE (SOC)" }), _jsx("div", { className: "text-5xl font-bold text-yellow-500 mb-2", children: "78%" }), _jsx("p", { className: "text-primary-400 text-sm", children: "Current charge level" })] }), _jsxs(Card, { className: "p-8 text-center relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 w-40 h-40 bg-primary-500/10 rounded-full -mr-20 -mt-20" }), _jsx("p", { className: "text-primary-400 text-sm font-semibold mb-3", children: "CHARGE CYCLES" }), _jsx("div", { className: "text-5xl font-bold text-primary-400 mb-2", children: "247" }), _jsx("p", { className: "text-primary-400 text-sm", children: "Remaining: ~3,500+" })] })] }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.3 }, className: "mb-12", children: [_jsx("h2", { className: "text-2xl font-bold text-white mb-6", children: "State of Health Trend (8 Months)" }), _jsx(Card, { className: "p-6", children: _jsx(ResponsiveContainer, { width: "100%", height: 300, children: _jsxs(AreaChart, { data: healthData, children: [_jsx("defs", { children: _jsxs("linearGradient", { id: "colorSOH", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#10b981", stopOpacity: 0.8 }), _jsx("stop", { offset: "95%", stopColor: "#10b981", stopOpacity: 0 })] }) }), _jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#374151" }), _jsx(XAxis, { dataKey: "month", stroke: "#9ca3af" }), _jsx(YAxis, { stroke: "#9ca3af", domain: [95, 100] }), _jsx(Tooltip, { contentStyle: {
                                            backgroundColor: '#1f2937',
                                            border: '1px solid #374151',
                                            borderRadius: '8px',
                                        } }), _jsx(Area, { type: "monotone", dataKey: "soh", stroke: "#10b981", fillOpacity: 1, fill: "url(#colorSOH)" })] }) }) })] }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.4 }, className: "mb-12", children: [_jsx("h2", { className: "text-2xl font-bold text-white mb-6", children: "Degradation Rate by Cycle Range" }), _jsx(Card, { className: "p-6", children: _jsx(ResponsiveContainer, { width: "100%", height: 300, children: _jsxs(AreaChart, { data: degradationData, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#374151" }), _jsx(XAxis, { dataKey: "cycle", stroke: "#9ca3af" }), _jsx(YAxis, { stroke: "#9ca3af" }), _jsx(Tooltip, { contentStyle: {
                                            backgroundColor: '#1f2937',
                                            border: '1px solid #374151',
                                            borderRadius: '8px',
                                        } }), _jsx(Area, { type: "monotone", dataKey: "rate", stroke: "#f59e0b", fillOpacity: 0.6, fill: "#f59e0b" })] }) }) })] }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.5 }, className: "grid grid-cols-1 md:grid-cols-2 gap-6 mb-12", children: [_jsxs(Card, { className: "p-6", children: [_jsxs("h3", { className: "text-lg font-bold text-white mb-4 flex items-center gap-2", children: [_jsx(TrendingDown, { className: "w-5 h-5 text-yellow-500" }), "AI Predictions"] }), _jsxs("ul", { className: "space-y-3 text-primary-300 text-sm", children: [_jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-primary-500", children: "\u2022" }), _jsx("span", { children: "Estimated end-of-life: 2032" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-primary-500", children: "\u2022" }), _jsx("span", { children: "Projected SOH at 5000 cycles: 85%" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-primary-500", children: "\u2022" }), _jsx("span", { children: "Degradation rate: 0.52% per 500 cycles" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-primary-500", children: "\u2022" }), _jsx("span", { children: "Optimal temperature for longevity: 20-25\u00B0C" })] })] })] }), _jsxs(Card, { className: "p-6", children: [_jsxs("h3", { className: "text-lg font-bold text-white mb-4 flex items-center gap-2", children: [_jsx(Lightbulb, { className: "w-5 h-5 text-emerald-500" }), "Recommendations"] }), _jsxs("ul", { className: "space-y-3 text-primary-300 text-sm", children: [_jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2713" }), _jsx("span", { children: "Maintain cool storage temperatures" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2713" }), _jsx("span", { children: "Avoid frequent fast charging" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2713" }), _jsx("span", { children: "Keep SOC between 20-80% for storage" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2713" }), _jsx("span", { children: "Update firmware when available" })] })] })] })] }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.6 }, className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsx(Button, { variant: "primary", fullWidth: true, onClick: () => navigate('/battery-passport'), children: "View Passport" }), _jsx(Button, { variant: "secondary", fullWidth: true, onClick: () => navigate('/dashboard'), children: "Back to Dashboard" })] })] }));
}
