import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Shield } from 'lucide-react';
import { Layout, Button, Input } from '../components/Layout';
import { Card, Header } from '../components/Card';
export default function OwnershipOTPScreen() {
    const navigate = useNavigate();
    const [otp, setOtp] = useState('');
    return (_jsxs(Layout, { title: "OTP Verification", children: [_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, children: _jsx(Header, { title: "OTP Verification", subtitle: "Verify ownership transfer with one-time password", icon: _jsx(Shield, {}) }) }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, className: "max-w-md mx-auto", children: [_jsxs(Card, { className: "p-12 text-center mb-8", children: [_jsx("p", { className: "text-primary-400 text-sm font-semibold mb-2", children: "Enter OTP Code" }), _jsx("p", { className: "text-primary-300 text-sm mb-8", children: "Sent to new.owner@example.com" }), _jsx(Input, { type: "text", placeholder: "000000", value: otp, maxLength: 6, onChange: (e) => setOtp(e.target.value.replace(/\D/g, '')), className: "text-center text-4xl tracking-widest mb-6" }), _jsxs("p", { className: "text-primary-400 text-xs", children: ["Resend OTP in ", _jsx("span", { className: "font-bold", children: "30s" })] })] }), _jsxs(Card, { className: "p-6 mb-8", children: [_jsx("h3", { className: "text-lg font-bold text-white mb-4", children: "What Happens Next" }), _jsxs("ul", { className: "space-y-2 text-primary-300 text-sm", children: [_jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2022" }), _jsx("span", { children: "OTP will be verified securely" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2022" }), _jsx("span", { children: "Blockchain transaction will be initiated" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2022" }), _jsx("span", { children: "Digital signatures will be updated" })] }), _jsxs("li", { className: "flex gap-2", children: [_jsx("span", { className: "text-emerald-500", children: "\u2022" }), _jsx("span", { children: "New owner will be notified" })] })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsx(Button, { variant: "primary", fullWidth: true, disabled: otp.length !== 6, onClick: () => navigate('/ownership-verification'), children: "Verify" }), _jsx(Button, { variant: "secondary", fullWidth: true, onClick: () => navigate('/ownership-transfer'), children: "Back" })] })] })] }));
}
