import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Repeat2, User } from 'lucide-react';
import { Layout, Button, Input } from '../components/Layout';
import { Card, Header } from '../components/Card';
export default function OwnershipTransferScreen() {
    const navigate = useNavigate();
    const [newOwnerEmail, setNewOwnerEmail] = useState('');
    return (_jsxs(Layout, { title: "Ownership Transfer", children: [_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, children: _jsx(Header, { title: "Ownership Transfer", subtitle: "Secure blockchain-verified transfer with OTP confirmation", icon: _jsx(Repeat2, {}) }) }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, className: "mb-12", children: [_jsx("h2", { className: "text-2xl font-bold text-white mb-6", children: "Current Owner" }), _jsxs(Card, { className: "p-8", children: [_jsxs("div", { className: "flex items-center gap-4 mb-6", children: [_jsx("div", { className: "w-16 h-16 bg-primary-700 rounded-full flex items-center justify-center", children: _jsx(User, { className: "w-8 h-8 text-primary-400" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-primary-400 text-sm mb-1", children: "Owner Name" }), _jsx("p", { className: "text-2xl font-bold text-white", children: "John Doe" }), _jsx("p", { className: "text-primary-400 text-sm", children: "john.doe@example.com" })] })] }), _jsxs("div", { className: "bg-primary-700 p-4 rounded-lg", children: [_jsx("p", { className: "text-primary-400 text-xs mb-1", children: "Digital Signature" }), _jsx("p", { className: "font-mono text-sm text-primary-300", children: "0x7f8c8d9e4f3b2a1c5d6e7f8g" })] })] })] }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.3 }, className: "mb-12", children: [_jsx("h2", { className: "text-2xl font-bold text-white mb-6", children: "New Owner Information" }), _jsxs(Card, { className: "p-8 space-y-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-primary-300 text-sm font-semibold mb-3", children: "Email Address" }), _jsx(Input, { type: "email", placeholder: "new.owner@example.com", value: newOwnerEmail, onChange: (e) => setNewOwnerEmail(e.target.value), icon: _jsx(User, {}) })] }), _jsxs("div", { children: [_jsx("p", { className: "text-primary-400 text-sm mb-3", children: "Transfer Process" }), _jsx("div", { className: "space-y-2", children: [
                                            { step: 1, desc: 'Verify new owner email' },
                                            { step: 2, desc: 'Send OTP verification' },
                                            { step: 3, desc: 'Blockchain confirmation' },
                                            { step: 4, desc: 'Digital signature update' },
                                        ].map((item) => (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-8 h-8 bg-primary-700 rounded-full flex items-center justify-center text-sm font-bold text-primary-400", children: item.step }), _jsx("span", { className: "text-white", children: item.desc })] }, item.step))) })] })] })] }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.4 }, className: "mb-12", children: _jsxs(Card, { className: "p-6 bg-yellow-500/10 border-yellow-500/30", children: [_jsx("p", { className: "text-yellow-400 font-semibold mb-2", children: "\u26A0\uFE0F Security Notice" }), _jsx("p", { className: "text-primary-300 text-sm", children: "This action requires blockchain verification and digital signatures. The new owner will receive an OTP to confirm the transfer." })] }) }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.5 }, className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsx(Button, { variant: "primary", fullWidth: true, disabled: !newOwnerEmail.includes('@'), onClick: () => navigate('/ownership-otp'), children: "Continue to Verification" }), _jsx(Button, { variant: "secondary", fullWidth: true, onClick: () => navigate('/dashboard'), children: "Cancel" })] })] }));
}
