import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { History, Wrench } from 'lucide-react';
import { Layout, Button } from '../components/Layout';
import { Card, Header } from '../components/Card';
const serviceHistory = [
    { date: '2024-01-15', service: 'Routine Maintenance', technician: 'Tech-001', status: 'completed', notes: 'Battery health check passed' },
    { date: '2024-01-10', service: 'Firmware Update', technician: 'Tech-002', status: 'completed', notes: 'v2.4.1 installed' },
    { date: '2023-12-20', service: 'Diagnostics Scan', technician: 'Tech-001', status: 'completed', notes: 'All systems healthy' },
    { date: '2023-11-15', service: 'Installation', technician: 'Tech-003', status: 'completed', notes: 'Initial setup completed' },
];
export default function ServiceHistoryScreen() {
    const navigate = useNavigate();
    return (_jsxs(Layout, { title: "Service History", children: [_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, children: _jsx(Header, { title: "Service History", subtitle: "Complete maintenance and service timeline", icon: _jsx(History, {}) }) }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-12", children: [_jsxs(Card, { className: "p-6 text-center", children: [_jsx("p", { className: "text-primary-400 text-sm font-semibold mb-3", children: "Total Services" }), _jsx("p", { className: "text-4xl font-bold text-white", children: "4" })] }), _jsxs(Card, { className: "p-6 text-center", children: [_jsx("p", { className: "text-primary-400 text-sm font-semibold mb-3", children: "Last Service" }), _jsx("p", { className: "text-2xl font-bold text-white", children: "15 Jan 2024" })] }), _jsxs(Card, { className: "p-6 text-center", children: [_jsx("p", { className: "text-primary-400 text-sm font-semibold mb-3", children: "Status" }), _jsx("p", { className: "text-emerald-500 font-bold", children: "All Clear" })] })] }), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.3 }, children: [_jsx("h2", { className: "text-2xl font-bold text-white mb-6", children: "Service Records" }), _jsx("div", { className: "space-y-4 relative", children: serviceHistory.map((service, idx) => (_jsx(motion.div, { initial: { opacity: 0, x: -20 }, animate: { opacity: 1, x: 0 }, transition: { delay: 0.05 * idx }, children: _jsx(Card, { className: "p-6", children: _jsxs("div", { className: "flex items-start gap-4 mb-4", children: [_jsx("div", { className: "p-3 bg-primary-700 rounded-lg mt-1", children: _jsx(Wrench, { className: "w-5 h-5 text-primary-400" }) }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("h3", { className: "text-lg font-bold text-white", children: service.service }), _jsx("span", { className: "badge badge-success", children: service.status })] }), _jsxs("p", { className: "text-primary-400 text-sm mb-3", children: [service.date, " \u2022 Technician: ", service.technician] }), _jsx("p", { className: "text-white", children: service.notes })] })] }) }) }, idx))) })] }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.4 }, className: "mt-12", children: _jsx(Button, { variant: "secondary", fullWidth: true, onClick: () => navigate('/dashboard'), children: "Back to Dashboard" }) })] }));
}
